server:
  undertow:
    io-threads: 8
    worker-threads: 128
    buffer-size: 1024
    direct-buffers: true
common:
  static-dir: /data/static/game/
  jedis:
    enable: true
    password: 123456
    host: 172.17.0.1
  swagger:
    enable: true
    title: 24节气
    description: 24节气API文档
    version: 1.0.0
  http:
    enable: true